import dotenv from "dotenv";

dotenv.config({});

export const {
  HOST,
  PORT,
  DB_URL,
  JWT_SECRET,
  JWT_SECRET_IN,
  JWT_REFRESH,
  JWT_REFRESH_IN,
  EMAIL_USER,
  EMAIL_PASSWORD,
  CLIENT_URI,
  CLINIC_CONTACT_EMAIL,
  CLINIC_CONTACT_PHONE,
  CLINIC_REBOOK_URL,
  JWT_FORGOT_PASSWORD,
  JWT_FORGOT_PASSWORD_IN,
} = process.env;
